CREATE TABLE IF NOT EXISTS sp500 (
	`date` datetime NOT NULL PRIMARY KEY,
	`open` DECIMAL NOT NULL,
	`close` DECIMAL NOT NULL,
	`adj_close` DECIMAL NOT NULL,
	`high` DECIMAL NOT NULL,
	`low` DECIMAL NOT NULL,
	`volume` INT NOT NULL
);
